# Generated by scripts/generate_gambit_functions.js from kubejs/data/gambit_kits.json.
# Edit the registry and rerun the generator instead of hand-editing this file.

function gun:kits/single/marksman
function gun:kits/single/breacher
function gun:kits/single/flanker
function gun:kits/single/assault
function gun:kits/single/sniper
function gun:kits/single/ranger
function gun:kits/single/burst
function gun:kits/single/sentry
function gun:kits/single/covert
function gun:kits/single/gunslinger
