# Generated by scripts/generate_gambit_functions.js from kubejs/data/gambit_kits.json.
# Edit the registry and rerun the generator instead of hand-editing this file.

execute as @a[tag=marksman,gamemode=!creative,gamemode=!spectator,tag=!gun_optout] run function gun:kits/single/marksman
execute as @a[tag=breacher,gamemode=!creative,gamemode=!spectator,tag=!gun_optout] run function gun:kits/single/breacher
execute as @a[tag=flanker,gamemode=!creative,gamemode=!spectator,tag=!gun_optout] run function gun:kits/single/flanker
execute as @a[tag=assault,gamemode=!creative,gamemode=!spectator,tag=!gun_optout] run function gun:kits/single/assault
execute as @a[tag=sniper,gamemode=!creative,gamemode=!spectator,tag=!gun_optout] run function gun:kits/single/sniper
execute as @a[tag=ranger,gamemode=!creative,gamemode=!spectator,tag=!gun_optout] run function gun:kits/single/ranger
execute as @a[tag=burst,gamemode=!creative,gamemode=!spectator,tag=!gun_optout] run function gun:kits/single/burst
execute as @a[tag=sentry,gamemode=!creative,gamemode=!spectator,tag=!gun_optout] run function gun:kits/single/sentry
execute as @a[tag=covert,gamemode=!creative,gamemode=!spectator,tag=!gun_optout] run function gun:kits/single/covert
execute as @a[tag=gunslinger,gamemode=!creative,gamemode=!spectator,tag=!gun_optout] run function gun:kits/single/gunslinger
