# Generated by scripts/generate_gambit_functions.js from kubejs/data/gambit_kits.json.
# Edit the registry and rerun the generator instead of hand-editing this file.

tag @s remove marksman
tag @s remove breacher
tag @s remove flanker
tag @s remove assault
tag @s remove sniper
tag @s remove ranger
tag @s remove burst
tag @s remove sentry
tag @s remove covert
tag @s remove gunslinger
