# Generated by scripts/generate_gambit_functions.js from kubejs/data/gambit_kits.json.
# Edit the registry and rerun the generator instead of hand-editing this file.

function gun:selectors/clear_kits
tag @s add gunslinger
title @s actionbar [{"text":"Gunslinger Kit Selected","color":"dark_green"}]
playsound minecraft:entity.item.pickup player @s ~ ~ ~ 0.6 1.2
function gun:kits/clear_hotbar
execute if entity @s[team=red] run function gun:kits/single/gunslinger
execute if entity @s[team=blue] run function gun:kits/single/gunslinger
execute if entity @s[team=red] run function gun:rations/give_random_self
execute if entity @s[team=blue] run function gun:rations/give_random_self
execute if entity @s[tag=in_range] run function gun:range/equip
