const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const registryPath = path.join(root, 'kubejs', 'data', 'gambit_kits.json');
const functionsRoot = path.join(root, 'GunFight', 'data', 'gun', 'functions');
const checkMode = process.argv.includes('--check');
const checkFailures = [];
const generatedHeader = [
  '# Generated by scripts/generate_gambit_functions.js from kubejs/data/gambit_kits.json.',
  '# Edit the registry and rerun the generator instead of hand-editing this file.',
  ''
];

function readRegistry() {
  const raw = JSON.parse(fs.readFileSync(registryPath, 'utf8'));
  const kits = Array.isArray(raw.kits) ? raw.kits : [];
  const seen = new Set();
  for (const kit of kits) {
    if (!kit || typeof kit.id !== 'string' || !/^[a-z0-9_]+$/.test(kit.id)) {
      throw new Error(`Invalid kit id: ${kit && kit.id}`);
    }
    if (seen.has(kit.id)) throw new Error(`Duplicate kit id: ${kit.id}`);
    seen.add(kit.id);
    if (!kit.display || !kit.color) throw new Error(`Kit ${kit.id} needs display and color`);
    const selector = kit.selector || {};
    for (const key of ['top', 'middle', 'bottom']) {
      if (!selector[key]) throw new Error(`Kit ${kit.id} selector is missing ${key}`);
    }
    const singlePath = path.join(functionsRoot, 'kits', 'single', `${kit.id}.mcfunction`);
    if (!fs.existsSync(singlePath)) throw new Error(`Missing kit loadout function: ${singlePath}`);
  }
  if (kits.length === 0) throw new Error('No kits found in registry');
  return kits;
}

function writeFunction(relativePath, lines) {
  const target = path.join(functionsRoot, relativePath);
  const content = `${lines.join('\n')}\n`;
  if (checkMode) {
    let current = null;
    try {
      current = fs.readFileSync(target, 'utf8');
    } catch (e) {
      checkFailures.push(`${relativePath} is missing`);
      return;
    }
    if (current !== content) checkFailures.push(`${relativePath} is out of date`);
    return;
  }
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, content, 'utf8');
}

function noKitTagSelector(kits) {
  return kits.map((kit) => `tag=!${kit.id}`).join(',');
}

function selectorPadCondition(kit) {
  const selector = kit.selector;
  return `if block ~ ~-1 ~ ${selector.top} if block ~ ~-2 ~ ${selector.middle} if block ~ ~-3 ~ ${selector.bottom}`;
}

function generateSelectorFunctions(kits) {
  for (const kit of kits) {
    writeFunction(`selectors/${kit.id}.mcfunction`, [
      ...generatedHeader,
      'function gun:selectors/clear_kits',
      `tag @s add ${kit.id}`,
      `title @s actionbar [{"text":"${kit.display} Kit Selected","color":"${kit.color}"}]`,
      'playsound minecraft:entity.item.pickup player @s ~ ~ ~ 0.6 1.2',
      'function gun:kits/clear_hotbar',
      `execute if entity @s[team=red] run function gun:kits/single/${kit.id}`,
      `execute if entity @s[team=blue] run function gun:kits/single/${kit.id}`,
      'execute if entity @s[team=red] run function gun:rations/give_random_self',
      'execute if entity @s[team=blue] run function gun:rations/give_random_self',
      'execute if entity @s[tag=in_range] run function gun:range/equip'
    ]);
  }
}

function generateKitTick(kits) {
  const lines = [
    ...generatedHeader,
    '# Kit selector tick - detect players standing on kit selection blocks',
    '# Lobby selection is always available for lobby players.'
  ];
  for (const kit of kits) {
    lines.push(`execute as @a[team=lobby,tag=!${kit.id},gamemode=adventure] at @s ${selectorPadCondition(kit)} run function gun:selectors/${kit.id}`);
  }
  lines.push('', '# TDM: allow pad selection directly for active Red/Blue players.');
  for (const team of ['Red', 'Blue']) {
    for (const kit of kits) {
      lines.push(`execute as @a[tag=${team},tag=!${kit.id},gamemode=adventure] at @s ${selectorPadCondition(kit)} run function gun:selectors/${kit.id}`);
    }
  }
  writeFunction('selectors/kit_tick.mcfunction', lines);
}

function generateLobbyTick(kits) {
  const noKit = noKitTagSelector(kits);
  const lines = [
    ...generatedHeader,
    '# Lobby tick - effects, guide book, sumo handling',
    'execute as @a[tag=gun_optout] run title @s actionbar [{"text":"Spectate Mode","color":"yellow","bold":true},{"text":" - use ","color":"gray"},{"text":"/play","color":"green"},{"text":" to queue","color":"gray"}]',
    '',
    '# Kit display - show selected kit in actionbar for queued lobby players (suppressed in range)'
  ];
  for (const kit of kits) {
    lines.push(`execute as @a[team=lobby,tag=!gun_optout,tag=!in_range,gamemode=adventure,tag=${kit.id}] run title @s actionbar [{"text":"Kit: ","color":"gray"},{"text":"${kit.display}","color":"${kit.color}","bold":true}]`);
  }
  lines.push(
    `execute as @a[team=lobby,tag=!gun_optout,tag=!in_range,gamemode=adventure,${noKit}] run title @s actionbar {"text":"No kit currently selected","color":"gray","italic":true}`,
    '',
    '# Keep active match players synced before lobby-only systems run.',
    'function gun:teams/repair',
    '',
    '# Sumo tag: lobby players standing on white or red wool in the sumo arena get the tag',
    'execute as @a[tag=!Red,tag=!Blue,x=-44,y=102,z=32,dx=13,dy=5,dz=13] at @s if block ~ ~-1 ~ minecraft:white_wool run tag @s add sumo',
    'execute as @a[tag=!Red,tag=!Blue,x=-44,y=102,z=32,dx=13,dy=5,dz=13] at @s if block ~ ~-1 ~ minecraft:red_wool run tag @s add sumo',
    '# Reset grace timer while standing on wool',
    'execute as @a[tag=!Red,tag=!Blue,tag=sumo] at @s if block ~ ~-1 ~ minecraft:white_wool run scoreboard players set @s sumo_grace 0',
    'execute as @a[tag=!Red,tag=!Blue,tag=sumo] at @s if block ~ ~-1 ~ minecraft:red_wool run scoreboard players set @s sumo_grace 0',
    '# Increment grace for tagged players not standing on wool (covers jumping, knockback, leaving arena)',
    'execute as @a[tag=!Red,tag=!Blue,tag=sumo] at @s unless block ~ ~-1 ~ minecraft:white_wool unless block ~ ~-1 ~ minecraft:red_wool run scoreboard players add @s sumo_grace 1',
    '# Remove tag after 20 ticks (1 second) continuously off wool',
    'execute as @a[tag=sumo,scores={sumo_grace=20..}] run tag @s remove sumo',
    '# Sync sumo team from tag (team controls PvP via friendlyFire)',
    'execute as @a[tag=!Red,tag=!Blue,tag=sumo,team=!sumo] run team join sumo @s',
    'execute as @a[tag=!Red,tag=!Blue,tag=!sumo,team=sumo] run function gun:teams/join_lobby',
    '',
    'effect give @a[team=lobby] saturation 16 1 true',
    'effect give @a[team=lobby] regeneration 5 1 true',
    'tag @a[team=lobby,tag=!Red,tag=!Blue] add gun_in_lobby',
    'tag @a[tag=Red] remove gun_in_lobby',
    'tag @a[tag=Blue] remove gun_in_lobby',
    'tag @a[team=!lobby] remove gun_in_lobby',
    'effect give @a[team=sumo] saturation 16 1 true',
    'effect give @a[team=sumo] regeneration 5 25 true',
    'effect give @a[team=red] speed 2 0 true',
    'effect give @a[team=blue] speed 2 0 true',
    '',
    '# Shooting range: volume x=-26..27, y=96..107, z=70..107',
    'execute as @a[team=lobby,tag=!gun_optout,gamemode=adventure,tag=!in_range,x=-26,y=96,z=70,dx=54,dy=12,dz=38] run tag @s add in_range'
  );
  for (const kit of kits) {
    lines.push(`execute as @a[tag=in_range,tag=!range_kitted,tag=${kit.id}] run function gun:range/equip`);
  }
  lines.push(
    'execute as @a[tag=in_range,tag=gun_in_lobby] unless entity @s[x=-26,y=96,z=70,dx=54,dy=12,dz=38] run function gun:range/exit',
    'execute as @a[tag=in_range,tag=!gun_in_lobby] run tag @s remove in_range',
    'execute as @a[tag=in_range,tag=!gun_in_lobby] run tag @s remove range_kitted'
  );
  writeFunction('lobby/tick.mcfunction', lines);
}

function generateEquipFunctions(kits) {
  writeFunction('selectors/clear_kits.mcfunction', [
    ...generatedHeader,
    ...kits.map((kit) => `tag @s remove ${kit.id}`)
  ]);
  writeFunction('kits/equip.mcfunction', [
    ...generatedHeader,
    ...kits.map((kit) => `execute as @a[tag=${kit.id},gamemode=!creative,gamemode=!spectator,tag=!gun_optout] run function gun:kits/single/${kit.id}`)
  ]);
  writeFunction('kits/single/equip.mcfunction', [
    ...generatedHeader,
    ...kits.map((kit) => `function gun:kits/single/${kit.id}`)
  ]);
  writeFunction('range/equip.mcfunction', [
    ...generatedHeader,
    "# Equip the player's currently selected kit for shooting range use.",
    '# Called on range entry (if kit already selected) and on kit pad selection while in range.',
    'clear @s',
    ...kits.map((kit) => `execute if entity @s[tag=${kit.id}] run function gun:kits/single/${kit.id}`),
    'item replace entity @s inventory.25 with tacz:ammo_box{AllTypeCreative:1b}',
    'tag @s add range_kitted'
  ]);
}

function generateStartFunctions(kits) {
  const noKit = noKitTagSelector(kits);
  writeFunction('starts/general.mcfunction', [
    ...generatedHeader,
    'effect clear @a[gamemode=!creative,gamemode=!spectator,tag=!gun_optout]',
    'execute as @a[gamemode=!creative,gamemode=!spectator,tag=!gun_optout] run data modify entity @s FoodSaturationLevel set value 20.0f',
    'clear @a[gamemode=!creative,gamemode=!spectator,tag=!gun_optout]',
    'tag @a[gamemode=!creative,gamemode=!spectator] remove gun_in_lobby',
    'yawp global add flag item-drop Denied',
    'yawp global add flag access-container Denied',
    'yawp global add flag use-blocks Denied',
    'gamerule keepInventory true',
    'lockserver',
    'gamerule reducedDebugInfo true',
    'gamerule announceAdvancements false',
    'gamerule doDaylightCycle false',
    'time set 6000',
    'gamerule doWeatherCycle false',
    'weather clear',
    'gamerule doImmediateRespawn true',
    'tag @a remove gun_dead',
    'tag @a remove gun_just_died',
    'tag @a remove gun_spec_tp_pending',
    'tag @a remove gun_in_match',
    'scoreboard players set @a tdm_respawn_timer 0',
    'scoreboard players set @a spec_respawn_timer 0',
    'scoreboard players set @a gun_downs 0',
    'gambit_reset_downs',
    'execute as @a[gamemode=!creative] run scoreboard players operation @s gun_deaths_prev = @s gun_deaths',
    'execute as @a[gamemode=!creative] run scoreboard players operation @s tdm_deaths_counted = @s gun_deaths',
    'scoreboard players set #selectors selector_active 0',
    'execute if score #mode mode_respawns matches 1 run scoreboard players set #selectors selector_active 1',
    `execute as @a[${noKit},gamemode=!creative,gamemode=!spectator,tag=!gun_optout] run tag @s add assault`,
    'function gun:kits/armor',
    'function gun:kits/equip',
    'effect give @a[gamemode=!creative,gamemode=!spectator,tag=!gun_optout] minecraft:regeneration 5 255 true',
    'execute as @a[gamemode=!creative,gamemode=!spectator,tag=!gun_optout] run function gun:rations/give_random_self',
    'tag @a[gamemode=!creative,gamemode=!spectator,tag=!gun_optout] add gun_in_match',
    'function gun:countdown/start',
    'function gun:teams/repair',
    'schedule clear gun:selectors/loop',
    'execute if score #mode mode_respawns matches 1 run schedule function gun:selectors/loop 1t',
    'schedule function gun:death/loop 1t'
  ]);

  const tournamentLines = [
    ...generatedHeader,
    'effect clear @a[tag=Red,gamemode=!creative,gamemode=!spectator]',
    'effect clear @a[tag=Blue,gamemode=!creative,gamemode=!spectator]',
    'execute as @a[tag=Red,gamemode=!creative,gamemode=!spectator] run data modify entity @s FoodSaturationLevel set value 20.0f',
    'execute as @a[tag=Blue,gamemode=!creative,gamemode=!spectator] run data modify entity @s FoodSaturationLevel set value 20.0f',
    'clear @a[tag=Red,gamemode=!creative,gamemode=!spectator]',
    'clear @a[tag=Blue,gamemode=!creative,gamemode=!spectator]',
    'tag @a[tag=Red,gamemode=!creative,gamemode=!spectator] remove gun_in_lobby',
    'tag @a[tag=Blue,gamemode=!creative,gamemode=!spectator] remove gun_in_lobby',
    'yawp global add flag item-drop Denied',
    'yawp global add flag access-container Denied',
    'yawp global add flag use-blocks Denied',
    'gamerule keepInventory true',
    'lockserver',
    'gamerule reducedDebugInfo true',
    'gamerule announceAdvancements false',
    'gamerule doDaylightCycle false',
    'time set 6000',
    'gamerule doWeatherCycle false',
    'weather clear',
    'gamerule doImmediateRespawn true',
    'tag @a remove gun_dead',
    'tag @a remove gun_just_died',
    'tag @a remove gun_spec_tp_pending',
    'tag @a remove gun_in_match',
    'scoreboard players set @a[tag=Red] tdm_respawn_timer 0',
    'scoreboard players set @a[tag=Blue] tdm_respawn_timer 0',
    'scoreboard players set @a[tag=Red] spec_respawn_timer 0',
    'scoreboard players set @a[tag=Blue] spec_respawn_timer 0',
    'scoreboard players set @a[tag=Red] gun_downs 0',
    'scoreboard players set @a[tag=Blue] gun_downs 0',
    'gambit_reset_downs',
    'execute as @a[tag=Red,gamemode=!creative] run scoreboard players operation @s gun_deaths_prev = @s gun_deaths',
    'execute as @a[tag=Blue,gamemode=!creative] run scoreboard players operation @s gun_deaths_prev = @s gun_deaths',
    'execute as @a[tag=Red,gamemode=!creative] run scoreboard players operation @s tdm_deaths_counted = @s gun_deaths',
    'execute as @a[tag=Blue,gamemode=!creative] run scoreboard players operation @s tdm_deaths_counted = @s gun_deaths',
    `execute as @a[tag=Red,${noKit},gamemode=!creative,gamemode=!spectator] run tag @s add assault`,
    `execute as @a[tag=Blue,${noKit},gamemode=!creative,gamemode=!spectator] run tag @s add assault`,
    'execute as @a[tag=Red,gamemode=!creative,gamemode=!spectator] run function gun:kits/armor_self',
    'execute as @a[tag=Blue,gamemode=!creative,gamemode=!spectator] run function gun:kits/armor_self'
  ];
  for (const kit of kits) {
    tournamentLines.push(`execute as @a[tag=Red,tag=${kit.id},gamemode=!creative,gamemode=!spectator] run function gun:kits/single/${kit.id}`);
    tournamentLines.push(`execute as @a[tag=Blue,tag=${kit.id},gamemode=!creative,gamemode=!spectator] run function gun:kits/single/${kit.id}`);
  }
  tournamentLines.push(
    'effect give @a[tag=Red,gamemode=!creative,gamemode=!spectator] minecraft:regeneration 5 255 true',
    'effect give @a[tag=Blue,gamemode=!creative,gamemode=!spectator] minecraft:regeneration 5 255 true',
    'execute as @a[tag=Red,gamemode=!creative,gamemode=!spectator] run function gun:rations/give_random_self',
    'execute as @a[tag=Blue,gamemode=!creative,gamemode=!spectator] run function gun:rations/give_random_self',
    'tag @a[tag=Red,gamemode=!creative,gamemode=!spectator] add gun_in_match',
    'tag @a[tag=Blue,gamemode=!creative,gamemode=!spectator] add gun_in_match',
    'execute as @a[tag=Red,gamemode=!creative,gamemode=!spectator] run item replace entity @s hotbar.2 from entity @s hotbar.3',
    'execute as @a[tag=Red,gamemode=!creative,gamemode=!spectator] run item replace entity @s hotbar.3 from entity @s hotbar.4',
    'execute as @a[tag=Red,gamemode=!creative,gamemode=!spectator] run item replace entity @s hotbar.4 with minecraft:air',
    'execute as @a[tag=Blue,gamemode=!creative,gamemode=!spectator] run item replace entity @s hotbar.2 from entity @s hotbar.3',
    'execute as @a[tag=Blue,gamemode=!creative,gamemode=!spectator] run item replace entity @s hotbar.3 from entity @s hotbar.4',
    'execute as @a[tag=Blue,gamemode=!creative,gamemode=!spectator] run item replace entity @s hotbar.4 with minecraft:air',
    'scoreboard objectives setdisplay sidebar',
    'function gun:countdown/start',
    'function gun:teams/repair',
    'schedule clear gun:selectors/loop',
    'schedule function gun:death/loop 1t'
  );
  writeFunction('starts/tournament_general.mcfunction', tournamentLines);
}

function main() {
  const kits = readRegistry();
  generateSelectorFunctions(kits);
  generateKitTick(kits);
  generateLobbyTick(kits);
  generateEquipFunctions(kits);
  generateStartFunctions(kits);
  if (checkMode) {
    if (checkFailures.length > 0) {
      for (const failure of checkFailures) console.error(`Out of date: ${failure}`);
      process.exitCode = 1;
      return;
    }
    console.log(`Generated Gambit functions are up to date for ${kits.length} kits.`);
    return;
  }
  console.log(`Generated Gambit functions for ${kits.length} kits.`);
}

main();
